### PR TITLE
prevent reconnecting during a transaction Action

### PR DESCRIPTION
**Pull request by fmoor**
fixes https://github.com/edgedb/edgedb-go/issues/67  
fixes https://github.com/edgedb/edgedb-go/issues/32

Previously the client would try to reconnect during an Action which could lead to failed or partial commits. This change makes it so the client doesn't reconnect during an Action. Instead it only checks the connection and reconnects if required before each Action attempt.

### CODE REVIEW

**Comment by fmoor** [comment]
Based on https://github.com/edgedb/edgedb-go/pull/62. WIP until upstream is merged.

**Comment by 1st1** [comment]
> Previously the client would try to reconnect during an Action which could lead to failed or partial commits. This change makes it so the client doesn't reconnect during an Action. Instead it only checks the connection and reconnects if required before each Action attempt.

What happens if there's a disconnect during `Retry()` call?

**Comment by fmoor** [comment]
> What happens if there's a disconnect during Retry() call?

`Retry()` ensures a connection before every retry attempt and only retries errors tagged with `SHOULD_RETRY`.  It looks like all connection errors tagged with `SHOULD_RETRY` are also tagged with `SHOULD_RECONNECT`. So to answer the question it would try to reconnect, then if successful re-run the callback.

**Review by 1st1 — APPROVED** [review]

**Comment by 1st1** [comment]
> Retry() ensures a connection before every retry attempt and only retries errors tagged with SHOULD_RETRY. It looks like all connection errors tagged with SHOULD_RETRY are also tagged with SHOULD_RECONNECT. So to answer the question it would try to reconnect, then if successful re-run the callback.

Yeah, so the behavior is the same as in Python/JS; this answers my question.

**Pull request merged**
